INSERT INTO countries (COUNTRY_ID, COUNTRY_NAME) VALUES (1, 'USA');
INSERT INTO countries (COUNTRY_ID, COUNTRY_NAME) VALUES (2, 'INDIA');

INSERT INTO state (STATE_ID, STATE_NAME,COUNTRY_ID) VALUES (1, 'MAHARASHTRA',2);
INSERT INTO state (STATE_ID, STATE_NAME,COUNTRY_ID) VALUES (2, 'AP',2);

INSERT INTO state (STATE_ID, STATE_NAME,COUNTRY_ID) VALUES (3, 'TEXAS',1);
INSERT INTO state (STATE_ID, STATE_NAME,COUNTRY_ID) VALUES (4, 'FLORIDA',1);




INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (1, 'PUNE',1);
INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (2, 'MUMBAI',1);

INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (3, 'HYD',2);
INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (4, 'VELLOR',2);



INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (5, 'DALLAS',3);
INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (6, 'AUSTIN',3);

INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (7, 'MIAMI',4);
INSERT INTO cities (CITY_ID, CITY_NAME,STATE_ID) VALUES (8, 'KEYWEST',4);
